const state={cities:[],city:null,venues:[],filter:"All",selectedVenue:null};
const $=s=>document.querySelector(s);
const cityInput=$("#cityInput"), cityList=$("#cityList"), grid=$("#venueGrid"), count=$("#resultCount"), note=$("#catalogNote"), filters=$("#filters");
const popularIds=["dallas-tx","new-york-ny","los-angeles-ca","chicago-il","orlando-fl","boston-ma"];
const seededCenters={"dallas-tx":[32.7767,-96.797],"new-york-ny":[40.7128,-74.006],"los-angeles-ca":[34.0522,-118.2437],"chicago-il":[41.8781,-87.6298],"orlando-fl":[28.5383,-81.3792],"boston-ma":[42.3601,-71.0589],"washington-dc":[38.9072,-77.0369],"philadelphia-pa":[39.9526,-75.1652],"seattle-wa":[47.6062,-122.3321],"houston-tx":[29.7604,-95.3698]};
function cityId(c){if(c.name==="Washington"&&c.state==="DC")return "washington-dc";return `${c.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}-${c.state.toLowerCase()}`}
function esc(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function normalize(v=""){return String(v).toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function osmEmbed(lat,lon){const d=.20;return `https://www.openstreetmap.org/export/embed.html?bbox=${lon-d}%2C${lat-d}%2C${lon+d}%2C${lat+d}&layer=mapnik&marker=${lat}%2C${lon}`}
function osmLink(lat,lon){return `https://www.openstreetmap.org/?mlat=${lat}&mlon=${lon}#map=12/${lat}/${lon}`}
async function loadJSON(url,fallback){try{const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error(r.status);return await r.json()}catch{return fallback}}
async function init(){const raw=await loadJSON("./top-100-cities.json",[]);state.cities=raw.map(c=>{const id=cityId(c),center=seededCenters[id];return {...c,id,label:`${c.name}, ${c.state}`,lat:center?.[0]??null,lon:center?.[1]??null}});cityList.innerHTML=state.cities.map(c=>`<option value="${esc(c.label)}"></option>`).join("");$("#popularCities").innerHTML=popularIds.map(id=>{const c=state.cities.find(x=>x.id===id);return c?`<button class="city-chip" data-city="${c.id}">${esc(c.name)}</button>`:""}).join("");document.addEventListener("click",e=>{const b=e.target.closest("[data-city]");if(b)selectCityById(b.dataset.city)});const requested=new URLSearchParams(location.search).get("city");await selectCityById(requested&&state.cities.some(c=>c.id===requested)?requested:"dallas-tx");const status=await loadJSON("./data/refresh-status.json",null);if(status?.lastRefresh)note.dataset.refresh=`Catalog refreshed ${status.lastRefresh}`}
function findCity(value){const n=normalize(value);return state.cities.find(c=>normalize(c.label)===n||normalize(c.name)===n)||state.cities.find(c=>normalize(c.label).includes(n)||normalize(c.name).includes(n))}
async function geocodeCity(city){if(Number.isFinite(city.lat)&&Number.isFinite(city.lon))return city;const q=encodeURIComponent(city.query||city.label);const urls=[`https://photon.komoot.io/api/?limit=1&q=${q}`,`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=us&q=${q}`];for(const url of urls){try{const r=await fetch(url,{headers:{Accept:"application/json"}});if(!r.ok)continue;const d=await r.json();let lat,lon;if(d?.features?.[0]){lon=Number(d.features[0].geometry.coordinates[0]);lat=Number(d.features[0].geometry.coordinates[1])}else if(d?.[0]){lat=Number(d[0].lat);lon=Number(d[0].lon)}if(Number.isFinite(lat)&&Number.isFinite(lon)){city.lat=lat;city.lon=lon;return city}}catch{}}return city}
async function selectCityById(id){const city=state.cities.find(c=>c.id===id);if(!city)return;state.city=await geocodeCity(city);cityInput.value=city.label;history.replaceState(null,"",`?city=${encodeURIComponent(city.id)}`);await loadCity()}
async function loadCity(){const city=state.city;$("#mapTitle").textContent=city.label;if(Number.isFinite(city.lat)&&Number.isFinite(city.lon)){$("#cityMap").src=osmEmbed(city.lat,city.lon);$("#openMapLink").href=osmLink(city.lat,city.lon)}else{$("#cityMap").removeAttribute("src");$("#openMapLink").removeAttribute("href")}state.venues=await loadJSON(`./data/venues/${city.id}.json`,[]);state.filter="All";renderFilters();renderVenues()}
function renderFilters(){const cats=["All",...new Set(state.venues.map(v=>v.category||"Activity"))].slice(0,10);filters.innerHTML=cats.map(c=>`<button class="filter-chip ${c===state.filter?"active":""}" data-filter="${esc(c)}">${esc(c)}</button>`).join("");filters.onclick=e=>{const b=e.target.closest("[data-filter]");if(!b)return;state.filter=b.dataset.filter;renderFilters();renderVenues()}}
function detailsLine(v){const bits=[];if(v.minimum)bits.push(v.minimum);if(v.eligibility)bits.push(v.eligibility);return bits.join(" · ")}
function renderVenues(){const shown=state.filter==="All"?state.venues:state.venues.filter(v=>(v.category||"Activity")===state.filter);count.textContent=`${shown.length} ${shown.length===1?"place":"places"}`;note.textContent=state.venues.length?`${note.dataset.refresh||"Catalog data loaded"}. Published rates are linked to their source; discovered venues are labeled separately.`:`This city does not have a generated catalog file yet. The GitHub refresh workflow will add venues without needing a server.`;if(!shown.length){grid.innerHTML=`<div class="empty-state"><h3>No cached venues yet for ${esc(state.city.label)}</h3><p>The static site is working. This city will fill in when the scheduled GitHub catalog refresh runs. You can still create a custom group now.</p><button class="primary-btn" id="customGroup" style="margin-top:20px;padding:14px 20px">Create a custom group</button></div>`;$("#customGroup").onclick=()=>openGroup({name:`${state.city.name} activity`,minimum:""});return}grid.innerHTML=shown.map(v=>{const published=Boolean(v.sourceBacked);const rate=published?(v.groupPrice||"See official group page"):(v.groupPrice||"Group rate not published in catalog");const source=v.groupSource||v.website||v.regularSource||"";const detail=(v.groupDetails||[]).join(" · ");return `<article class="venue-card"><div class="card-top"><span class="category">${esc(v.category||"Activity")}</span><span class="status-badge ${published?"":"discovery"}">${published?"SOURCE-BACKED":"DISCOVERED"}</span></div><h3>${esc(v.name)}</h3><div class="address">${esc(v.address||state.city.label)}</div><div class="rate-box"><div class="rate-label">${published?"GROUP INFORMATION":"RATE STATUS"}</div><div class="rate-main">${esc(rate)}</div>${detail?`<div class="rate-detail">${esc(detail)}</div>`:""}${v.savings?`<div class="savings">${esc(v.savings)}</div>`:""}${detailsLine(v)?`<div class="minimum">${esc(detailsLine(v))}</div>`:""}</div><div class="card-actions">${source?`<a class="source-link" href="${esc(source)}" target="_blank" rel="noopener">Official source ↗</a>`:`<a class="source-link" href="https://www.google.com/search?q=${encodeURIComponent(v.name+" "+state.city.label)}" target="_blank" rel="noopener">Find website ↗</a>`}<button class="group-btn" data-group="${esc(v.id)}">Start a group</button></div></article>`}).join("");grid.querySelectorAll("[data-group]").forEach(b=>b.onclick=()=>openGroup(state.venues.find(v=>v.id===b.dataset.group)))}
function openGroup(v){state.selectedVenue=v;$("#dialogVenue").textContent=v.name;$("#groupName").value=`${v.name} group`;const m=String(v.minimum||"").match(/\d+/);$("#groupTarget").value=m?m[0]:10;$("#groupDialog").showModal()}
$("#groupForm").addEventListener("submit",e=>{if(e.submitter?.value==="cancel")return;const groups=JSON.parse(localStorage.getItem("grouppass-groups")||"[]");groups.push({id:crypto.randomUUID?.()||Date.now(),venue:state.selectedVenue?.name||"Custom activity",city:state.city.label,name:$("#groupName").value,target:Number($("#groupTarget").value),date:$("#groupDate").value,createdAt:new Date().toISOString()});localStorage.setItem("grouppass-groups",JSON.stringify(groups));setTimeout(()=>alert("Group saved on this device."),0)});
$("#searchBtn").onclick=()=>{const c=findCity(cityInput.value);if(c)selectCityById(c.id);else alert("Choose a city from the list.")};cityInput.addEventListener("keydown",e=>{if(e.key==="Enter")$("#searchBtn").click()});$("#homeBtn").onclick=()=>scrollTo({top:0,behavior:"smooth"});
$("#locationBtn").onclick=()=>{if(!navigator.geolocation){alert("Location is not available in this browser.");return}const btn=$("#locationBtn");btn.textContent="Finding you…";navigator.geolocation.getCurrentPosition(async p=>{try{const u=`https://nominatim.openstreetmap.org/reverse?format=json&lat=${p.coords.latitude}&lon=${p.coords.longitude}`;const d=await(await fetch(u)).json();const name=d.address?.city||d.address?.town||d.address?.village||d.address?.county;const stateCode=d.address?.['ISO3166-2-lvl4']?.split('-')[1]||"";const city=state.cities.find(c=>normalize(c.name)===normalize(name)&&(!stateCode||c.state===stateCode))||state.cities.find(c=>normalize(c.name)===normalize(name));if(city)await selectCityById(city.id);else{state.city={id:"near-me",name:name||"Near me",state:stateCode,label:[name,stateCode].filter(Boolean).join(", "),lat:p.coords.latitude,lon:p.coords.longitude};state.venues=[];await loadCity()}}catch{alert("We found your location but could not match it to the city list.")}finally{btn.textContent="⌖ Use my location"}},()=>{btn.textContent="⌖ Use my location";alert("Location permission was not granted.")},{enableHighAccuracy:false,timeout:10000})};
init();